### PR TITLE
V2 nextjs

### PR DESCRIPTION
**Pull request by conradkirschner**
Updated to ssr version with use of nextjs

### CODE REVIEW

**Comment by roechi** [comment]
@conradkirschner @bogdangi Looks great! Two minor things:
- the teaser image stretches and warps on large view ports
- the tile for _mle-sagemaker-experiments-tool_ cannot be loaded, since the linked resource https://asideas-github-cache.herokuapp.com/idealo/mle-sagemaker-experiments-tool responds with 404

**Comment by conradkirschner** [comment]
@roechi updated hero image (teaser image) for support responsive layout 

- for mle-sagemaker-experiments-tool -> it's internal ( https://github.com/idealo/mle-sagemaker-experiments-tool )
=> not sure if it should be open source or not ... if not I should be removed to avoid errors

**Comment by conradkirschner** [comment]
@roechi updated hero/teaser image to support responsive layout

@bogdangi 
mle-sagemaker-experiments-tool, is currently not opensource... should it be removed from this repo?

**Comment by bogdangi** [comment]
@conradkirschner did you rebase on top of develop? (the mle-sagemaker-experiments-tool is deleted in the develop branch)

**Comment by conradkirschner** [comment]
@bogdangi  I had, but during this "big" migration, I deleted everything for cleanup and restored it part by part, therefore it isn't in... but I see your commit and restored project.js - restored it

**Comment by roechi** [comment]
Looks fine to me!

**Pull request merged**
